# Generated by Django 5.2 on 2025-05-17 03:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('office_supplies', '0013_requestitem'),
        ('office_supplies', '0009_add_created_at'),
    ]

    operations = []  # Empty operations since this is just a merge
