# Generated by Django 5.2 on 2025-05-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_merge_user_fields'),
        ('reports', '0004_add_user_field'),
    ]

    operations = [
    ]
