# Generated by Django 5.2 on 2025-05-17 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_user_field'),
        ('reports', '0005_merge_20250516_2123'),
    ]

    operations = [
    ]
