# Generated by Django 5.2 on 2025-05-17 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet_supplies', '0015_add_created_at'),
        ('vet_supplies', '0016_merge_migrations'),
    ]

    operations = [
    ]
